# development:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   # host: devdb
#   database: glucose_level_test
#   pool: 5
#   username: root
#   password: qazplm123

development:
  adapter: postgresql
  host: localhost
  encoding: utf8
  reconnect: false
  database: glucose_level_test
  pool: 5
  username: postgres
  password: postgres